upload diff before failing
Signed-off-by: Caroline Russell <caroline@appthreat.dev>

diff --git a/.github/workflows/snapshot-tests.yml b/.github/workflows/snapshot-tests.yml
--- a/.github/workflows/snapshot-tests.yml
+++ b/.github/workflows/snapshot-tests.yml
@@ -86,3 +86,17 @@ jobs:
       - name: Test BOMs
         run: |
           python test/diff/diff_tests.py
+          if test -f /home/runner/work/cdxgen-samples/diffs.json; then
+            echo "status=FAILED" >> "$GITHUB_ENV"
+          fi
+
+      - name: Upload diff
+        if: ${{ env.status == 'FAILED' }}
+        uses: actions/upload-artifact@v4
+        with:
+            name: diff
+            path: /home/runner/work/cdxgen-samples/diffs.json
+
+      - name: Exit with error
+        if: ${{ env.status == 'FAILED' }}
+        run: exit 1
